version: '3.9'

services:
  payment-localstack:
    image: localstack/localstack:latest
    container_name: payment-localstack
    environment:
      - SERVICES=sqs,sns,dynamodb
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - dev-networks

  mock-server:
    container_name: app.ze-burger-payments.orders-mock.dev
    image: mockoon/cli:latest
    command: [ "--data", "data", "--port", "8002" ]
    ports:
      - 8002:8002
    volumes:
      - ./orders-mock.json:/data:readonly
    networks:
      - dev-networks

networks:
  dev-networks:
    driver: bridge
