version: '3.9'

services:
  dev-app-payment:
    container_name: app.ze-burger-payments.dev
    env_file: .env
    build:
      dockerfile: ./infra/docker/local/Dockerfile
      context: ./
    volumes:
      - .:/app
    ports:
      - 8081:8081
    networks:
      - dev-networks

networks:
  dev-networks:
    driver: bridge
