definitions:
  controller.Response:
    properties:
      data: {}
      error:
        example: ""
        type: string
    type: object
  input.PaymentDto:
    properties:
      order_id:
        type: integer
      type:
        type: string
    required:
    - order_id
    - type
    type: object
  swagger.InternalServerErrorResponse:
    properties:
      data: {}
      error:
        example: Internal server error
        type: string
    type: object
  swagger.ResourceNotFoundResponse:
    properties:
      data: {}
      error:
        example: Resource not found
        type: string
    type: object
info:
  contact: {}
paths:
  /payments:
    post:
      consumes:
      - application/json
      description: Start payment process for a certain order
      parameters:
      - description: Payment properties
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/input.PaymentDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/controller.Response'
            - properties:
                data:
                  type: string
              type: object
        "404":
          description: Not Found
          schema:
            allOf:
            - $ref: '#/definitions/swagger.ResourceNotFoundResponse'
            - properties:
                data:
                  type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/swagger.InternalServerErrorResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: Start payment process
      tags:
      - Payments
  /payments/{id}/cancel:
    delete:
      consumes:
      - application/json
      description: Payment cancelation endpoint
      parameters:
      - description: Payment ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/swagger.InternalServerErrorResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: Payment cancelation endpoint
      tags:
      - Payments
  /payments/{id}/notification:
    post:
      consumes:
      - application/json
      description: Payment confirmation webhook
      parameters:
      - description: Payment ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            allOf:
            - $ref: '#/definitions/swagger.ResourceNotFoundResponse'
            - properties:
                data:
                  type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/swagger.InternalServerErrorResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: Payment confirmation webhook
      tags:
      - Payments
  /payments/{id}/status:
    get:
      consumes:
      - application/json
      description: Get status for order last payment try
      parameters:
      - description: Payment ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.Response'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/swagger.InternalServerErrorResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: Get status for last payment
      tags:
      - Payments
swagger: "2.0"
